# Generated by Django 5.2.17 on 2026-09-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0002_seed_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="brand",
        ),
    ]
