# Generated by Django 5.2.17 on 2026-09-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0006_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(
                choices=[
                    ("order", "An order"),
                    ("product", "A product question"),
                    ("other", "Something else"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
