# Generated by Django 5.2.17 on 2026-09-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0008_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="concern",
            name="accent_color",
            field=models.CharField(
                default="#c2486b",
                help_text="Hex accent color used to give this concern's routines a distinct identity.",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="concern",
            name="ingredient_explanation",
            field=models.CharField(
                blank=True,
                help_text="One-sentence, jargon-free explanation of why the key ingredient works.",
                max_length=240,
            ),
        ),
    ]
